# Generated by Django 5.2.1 on 2025-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_cover_image_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
